name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
      - name: Checkout repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup bootstrap Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry for Linux
        if: runner.os == 'Linux'
        run: |
          curl -sSL https://install.python-poetry.org/ | python - --version 1.1.5
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Poetry for Windows
        if: runner.os == 'Windows'
        run: |
          (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python - --version 1.1.5
          echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Python dependencies (Linux-only)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libgirepository1.0-dev libcairo2-dev qemu-utils libvirt-dev
      - name: Install Python dependencies
        run: make setup

      - name: Run hello-world
        run: make run

      - name: Run unit tests
        run: make test

      - name: Calculate code coverage
        run: make coverage
        if: matrix.python-version == '3.8'

      - name: Run black/flake8/isort/mypy
        run: make check
        if: matrix.python-version == '3.8'

      - name: Run ShellCheck
        if: runner.os == 'Linux' && matrix.python-version == '3.8'
        uses: ludeeus/action-shellcheck@0.5.0